export const SELECTED_FILTERS = 'SELECTED_FILTERS';
export const GET_HOTELS = 'GET_HOTELS';
export const ADD_ALL_HOTELS = 'ADD_ALL_HOTELS';
export const GET_HOTELS_REQUEST = 'GET_HOTELS_REQUEST';
export const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
export const GET_HOTELS_FAILURE = 'GET_HOTELS_FAILURE';
export const GET_HOTEL_ENTITYPAGE = 'GET_HOTEL_ENTITYPAGE';
export const GOT_HOTEL_ENTITY = 'GOT_HOTEL_ENTITY';