
export var filterOptions = [
    { display: "Homes", key: "isHome" },
    { display: "Family Friendly", key: "isFamilyFriendly" },
    { display: "I want free Breakfast", key: "includesBreakfast" },
    { display: "Book without credit card", key: "canBookwithoutCC" },
    { display: "Staycation", key: "isStaycation" },
  ];
  
  export var hotels = [
    {
      id: 123,
      name: "Dewdrop Mizu",
      rating: 10.0,
      reviewCount: 23,
      pricePerNight: 2229,
      imageSrc:
        "https://pix5.agoda.net/hotelImages/9808830/-1/e5bc2587c9cc396866d60ac22741102a.jpg?s=450x450",
      roomsRemaining: 9,
      hasFreeCancellation: true,
      includesBreakfast: true,
      isBestSeller: false,
      dinner: false,
      isHome: false,
      isFamilyFriendly : true,
      canBookwithoutCC : false,
      isStaycation : true,
      hasWifi : true,
      payAtHotel: true,
      isBooked : true,
      isReserved : true,
      hasHouseKeep : true,
      size : 200,
      desc : " Description about hotel"

    },
    {
      id: 124,
      name: "Lemon Tree Premier 1, Gurugram",
      rating: 5.6,
      reviewCount: 172,
      pricePerNight: 2533,
      imageSrc:
        "https://pix6.agoda.net/hotelImages/7539582/0/3593d62ac5bf45be9d6db27f1d0ab7d6.jpg?s=450x450",
      roomsRemaining: 22,
      hasFreeCancellation: false,
      includesBreakfast: true,
      isBestSeller: true,
      dinner: true,
      isHome : true,
      isFamilyFriendly : true,
      canBookwithoutCC: true,
      isStaycation : false,
      hasWifi : true,
      payAtHotel: true,
      isBooked : true,
      isReserved : true,
      hasHouseKeep : true,
      size : 200,
      desc : " Description about hotel"
    },
    {
      id: 125,
      name: "Fabhotel Raj Darbar",
      rating: 8.7,
      reviewCount: 12,
      pricePerNight: 2909,
      imageSrc:
        "https://pix5.agoda.net/hotelImages/5835986/-1/7ae4f98db071087c2b092d644fd2a381.jpg?s=450x450",
      roomsRemaining: 2,
      hasFreeCancellation: false,
      includesBreakfast: false,
      isBestSeller: true,
      dinner: true,
      isHome : false,
      isFamilyFriendly : true,
      canBookwithoutCC: true,
      isStaycation : true,
      hasWifi : true,
      payAtHotel: true,
      isBooked : true,
      isReserved : true,
      hasHouseKeep : true,
      size : 200,
      desc : " Description about hotel"
    },
    {
      id: 126,
      name: "Inde Hotel Cyber City - Cyber Hub",
      rating: 7.7,
      reviewCount: 23,
      pricePerNight: 2162,
      imageSrc:
        "https://pix6.agoda.net/hotelImages/5743495/-1/2d30646e201af101d43addd3e1c7d302.jpg?s=450x450",
      roomsRemaining: 14,
      hasFreeCancellation: true,
      includesBreakfast: false,
      isBestSeller: false,
      dinner: true,
      isHome : false,
      isFamilyFriendly : false,
      canBookwithoutCC : true,
      isStaycation : false,
      hasWifi : true,
      payAtHotel: false,
      isBooked : true,
      isReserved : false,
      hasHouseKeep : true,
      size : 200,
      desc : " Description about hotel"
    },
    {
      id: 127,
      name: "Glitz Westend Inn",
      rating: 8.5,
      reviewCount: 71,
      pricePerNight: 1989,
      imageSrc:
        "https://pix6.agoda.net/hotelImages/259/2599397/2599397_17081111390055329560.jpg?s=450x450",
      roomsRemaining: 8,
      hasFreeCancellation: true,
      includesBreakfast: false,
      isBestSeller: false,
      dinner: false,
      isHome : false,
      isFamilyFriendly : false,
      canBookwithoutCC : true,
      isStaycation : true,
      hasWifi : true,
      payAtHotel: true,
      isBooked : true,
      isReserved : true,
      hasHouseKeep : true,
      size : 200,
      desc : " Description about hotel"
    }
  
  ];
  

  